columnSuffix: null
contentColumnType: string
fieldGroup: 958462d0-9686-4c48-b82a-7ae58e612250 # Blog Post Fields
handle: postContent
instructions: 'content of the blog post'
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
