defaultPlacement: end
enableVersioning: true
handle: about
name: about
propagationMethod: all
siteSettings:
  c2cf97a7-0756-4827-8387-92c11910da4f: # blog
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
